//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.1434
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisualAsterisk.Manager.Controls.Properties {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizedStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedStrings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VisualAsterisk.Manager.Controls.Properties.LocalizedStrings", typeof(LocalizedStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm Delete 的本地化字符串。
        /// </summary>
        internal static string Common_ConfirmDelete {
            get {
                return ResourceManager.GetString("Common_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        internal static string Common_Delete {
            get {
                return ResourceManager.GetString("Common_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        internal static string Common_Edit {
            get {
                return ResourceManager.GetString("Common_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 and... 的本地化字符串。
        /// </summary>
        internal static string ExtensionContactControl_And {
            get {
                return ResourceManager.GetString("ExtensionContactControl_And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change Settings... 的本地化字符串。
        /// </summary>
        internal static string ExtensionContactControl_ChangeSettings {
            get {
                return ResourceManager.GetString("ExtensionContactControl_ChangeSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Done 的本地化字符串。
        /// </summary>
        internal static string ExtensionContactControl_Done {
            get {
                return ResourceManager.GetString("ExtensionContactControl_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If no answer after {0} seconds(s), CallButler will try 的本地化字符串。
        /// </summary>
        internal static string ExtensionContactControl_NoAnswer {
            get {
                return ResourceManager.GetString("ExtensionContactControl_NoAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If there is no answer, then... 的本地化字符串。
        /// </summary>
        internal static string ExtensionContactControl_NoAnswer2 {
            get {
                return ResourceManager.GetString("ExtensionContactControl_NoAnswer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 My IP Phone 的本地化字符串。
        /// </summary>
        internal static string ExtensionContactControl_PBXPhone {
            get {
                return ResourceManager.GetString("ExtensionContactControl_PBXPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} seconds... 的本地化字符串。
        /// </summary>
        internal static string ExtensionContactControl_Seconds {
            get {
                return ResourceManager.GetString("ExtensionContactControl_Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to delete this voicemail message? 的本地化字符串。
        /// </summary>
        internal static string VoicemailControl_ConfirmDelete {
            get {
                return ResourceManager.GetString("VoicemailControl_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Message {0} of {1} 的本地化字符串。
        /// </summary>
        internal static string VoicemailControl_MessageNumber {
            get {
                return ResourceManager.GetString("VoicemailControl_MessageNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NEW 的本地化字符串。
        /// </summary>
        internal static string VoicemailControl_New {
            get {
                return ResourceManager.GetString("VoicemailControl_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Messages 的本地化字符串。
        /// </summary>
        internal static string VoicemailControl_NoMessages {
            get {
                return ResourceManager.GetString("VoicemailControl_NoMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown Caller 的本地化字符串。
        /// </summary>
        internal static string VoicemailControl_UnknownCaller {
            get {
                return ResourceManager.GetString("VoicemailControl_UnknownCaller", resourceCulture);
            }
        }
    }
}
