using System;
using System.Collections.Generic;
using System.Text;

namespace VisualAsterisk.Asterisk
{
    public enum HangupCause
    {
        AST_CAUSE_UNALLOCATED,
        AST_CAUSE_NO_ROUTE_TRANSIT_NET,
        AST_CAUSE_NO_ROUTE_DESTINATION,
        AST_CAUSE_CHANNEL_UNACCEPTABLE,
        AST_CAUSE_CALL_AWARDED_DELIVERED,
        AST_CAUSE_NORMAL_CLEARING,
        AST_CAUSE_USER_BUSY,
        AST_CAUSE_NO_USER_RESPONSE,
        AST_CAUSE_NO_ANSWER,
        AST_CAUSE_CALL_REJECTED,
        AST_CAUSE_NUMBER_CHANGED,
        AST_CAUSE_DESTINATION_OUT_OF_ORDER,
        AST_CAUSE_INVALID_NUMBER_FORMAT,
        AST_CAUSE_FACILITY_REJECTED,
        AST_CAUSE_RESPONSE_TO_STATUS_ENQUIRY,
        AST_CAUSE_NORMAL_UNSPECIFIED,
        AST_CAUSE_NORMAL_CIRCUIT_CONGESTION,
        AST_CAUSE_NETWORK_OUT_OF_ORDER,
        AST_CAUSE_NORMAL_TEMPORARY_FAILURE,
        AST_CAUSE_SWITCH_CONGESTION,
        AST_CAUSE_ACCESS_INFO_DISCARDED,
        AST_CAUSE_REQUESTED_CHAN_UNAVAIL,
        AST_CAUSE_PRE_EMPTED,
        AST_CAUSE_FACILITY_NOT_SUBSCRIBED,
        AST_CAUSE_OUTGOING_CALL_BARRED,
        AST_CAUSE_INCOMING_CALL_BARRED,
        AST_CAUSE_BEARERCAPABILITY_NOTAUTH,
        AST_CAUSE_BEARERCAPABILITY_NOTAVAIL,
        AST_CAUSE_BEARERCAPABILITY_NOTIMPL,
        AST_CAUSE_CHAN_NOT_IMPLEMENTED,
        AST_CAUSE_FACILITY_NOT_IMPLEMENTED,
        AST_CAUSE_INVALID_CALL_REFERENCE,
        AST_CAUSE_INCOMPATIBLE_DESTINATION,
        AST_CAUSE_INVALID_MSG_UNSPECIFIED,
        AST_CAUSE_MANDATORY_IE_MISSING,
        AST_CAUSE_MESSAGE_TYPE_NONEXIST,
        AST_CAUSE_WRONG_MESSAGE,
        AST_CAUSE_IE_NONEXIST,
        AST_CAUSE_INVALID_IE_CONTENTS,
        AST_CAUSE_WRONG_CALL_STATE,
        AST_CAUSE_RECOVERY_ON_TIMER_EXPIRE,
        AST_CAUSE_MANDATORY_IE_LENGTH_ERROR,
        AST_CAUSE_PROTOCOL_ERROR,
        AST_CAUSE_INTERWORKING,

        /* Special Asterisk aliases */
        AST_CAUSE_BUSY,
        AST_CAUSE_FAILURE,
        AST_CAUSE_NORMAL,
        AST_CAUSE_NOANSWER,
        AST_CAUSE_CONGESTION,
        AST_CAUSE_UNREGISTERED,
        AST_CAUSE_NOTDEFINED,
        AST_CAUSE_NOSUCHDRIVER
    }
}
