//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3053
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisualAsterisk.Main.Properties {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizedStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedStrings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VisualAsterisk.Main.Properties.LocalizedStrings", typeof(LocalizedStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Telephony2 Corporation. All Rights Reserved 的本地化字符串。
        /// </summary>
        internal static string AboutForm_CopyrightPostfix {
            get {
                return ResourceManager.GetString("AboutForm_CopyrightPostfix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This software trial has expired and is unlicensed 的本地化字符串。
        /// </summary>
        internal static string AboutForm_Expired {
            get {
                return ResourceManager.GetString("AboutForm_Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///Trial license expires on {0} 的本地化字符串。
        /// </summary>
        internal static string AboutForm_ExpiresOn {
            get {
                return ResourceManager.GetString("AboutForm_ExpiresOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This software is licensed free of charge 的本地化字符串。
        /// </summary>
        internal static string AboutForm_FreeLicense {
            get {
                return ResourceManager.GetString("AboutForm_FreeLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Licensed to: {0} 的本地化字符串。
        /// </summary>
        internal static string AboutForm_LicensedTo {
            get {
                return ResourceManager.GetString("AboutForm_LicensedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Manager Version {0} 的本地化字符串。
        /// </summary>
        internal static string AboutForm_ManagerVersion {
            get {
                return ResourceManager.GetString("AboutForm_ManagerVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Server Version {0} 的本地化字符串。
        /// </summary>
        internal static string AboutForm_ServerVersion {
            get {
                return ResourceManager.GetString("AboutForm_ServerVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add a new option... 的本地化字符串。
        /// </summary>
        internal static string CallFlowView_AddNewOption {
            get {
                return ResourceManager.GetString("CallFlowView_AddNewOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add-on Module 的本地化字符串。
        /// </summary>
        internal static string CallFlowView_AddonModule {
            get {
                return ResourceManager.GetString("CallFlowView_AddonModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add/Remove Languages... 的本地化字符串。
        /// </summary>
        internal static string CallFlowView_AddRemoveLanguages {
            get {
                return ResourceManager.GetString("CallFlowView_AddRemoveLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Answer an incoming call 的本地化字符串。
        /// </summary>
        internal static string CallFlowView_AnswerCall {
            get {
                return ResourceManager.GetString("CallFlowView_AnswerCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ask the caller to choose a language 的本地化字符串。
        /// </summary>
        internal static string CallFlowView_AskChooseLanguage {
            get {
                return ResourceManager.GetString("CallFlowView_AskChooseLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The caller dials an option 的本地化字符串。
        /// </summary>
        internal static string CallFlowView_CallerDials {
            get {
                return ResourceManager.GetString("CallFlowView_CallerDials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings... 的本地化字符串。
        /// </summary>
        internal static string CallFlowView_CallSettings {
            get {
                return ResourceManager.GetString("CallFlowView_CallSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change... 的本地化字符串。
        /// </summary>
        internal static string CallFlowView_Change {
            get {
                return ResourceManager.GetString("CallFlowView_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Choose a Language 的本地化字符串。
        /// </summary>
        internal static string CallFlowView_ChooseLanguage {
            get {
                return ResourceManager.GetString("CallFlowView_ChooseLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to delete this department? 的本地化字符串。
        /// </summary>
        internal static string CallFlowView_ConfirmDeleteDepartment {
            get {
                return ResourceManager.GetString("CallFlowView_ConfirmDeleteDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Execute a Custom Script 的本地化字符串。
        /// </summary>
        internal static string CallFlowView_CustomScript {
            get {
                return ResourceManager.GetString("CallFlowView_CustomScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dial {0} for {1} 的本地化字符串。
        /// </summary>
        internal static string CallFlowView_Dial {
            get {
                return ResourceManager.GetString("CallFlowView_Dial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dial an Option 的本地化字符串。
        /// </summary>
        internal static string CallFlowView_DialAnOption {
            get {
                return ResourceManager.GetString("CallFlowView_DialAnOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Explain the available options 的本地化字符串。
        /// </summary>
        internal static string CallFlowView_ExplainOptions {
            get {
                return ResourceManager.GetString("CallFlowView_ExplainOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extension appears to have been deleted 的本地化字符串。
        /// </summary>
        internal static string CallFlowView_ExtDeleted {
            get {
                return ResourceManager.GetString("CallFlowView_ExtDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 For {0}, press {1}.
        ///
        /// 的本地化字符串。
        /// </summary>
        internal static string CallFlowView_ForDepartment {
            get {
                return ResourceManager.GetString("CallFlowView_ForDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 For a company directory, press pound.
        ///
        ///To repeat this menu, press star. 的本地化字符串。
        /// </summary>
        internal static string CallFlowView_ForDirectory {
            get {
                return ResourceManager.GetString("CallFlowView_ForDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If you know your party&apos;s Extension, you may dial it at any time.
        ///
        /// 的本地化字符串。
        /// </summary>
        internal static string CallFlowView_KnowParty {
            get {
                return ResourceManager.GetString("CallFlowView_KnowParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Since you have made changes to your language options, it is recommended that you update your Choose a Language Greeting to reflect these changes. 的本地化字符串。
        /// </summary>
        internal static string CallFlowView_LanguageChanges {
            get {
                return ResourceManager.GetString("CallFlowView_LanguageChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Main Menu.
        ///
        /// 的本地化字符串。
        /// </summary>
        internal static string CallFlowView_MainMenu {
            get {
                return ResourceManager.GetString("CallFlowView_MainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Main Menu Greeting 的本地化字符串。
        /// </summary>
        internal static string CallFlowView_MainMenuGreeting {
            get {
                return ResourceManager.GetString("CallFlowView_MainMenuGreeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Since you have made changes to your menu options, it is recommended that you update your Main Menu Greeting to reflect these changes. 的本地化字符串。
        /// </summary>
        internal static string CallFlowView_MenuOptionChanges {
            get {
                return ResourceManager.GetString("CallFlowView_MenuOptionChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Department 的本地化字符串。
        /// </summary>
        internal static string CallFlowView_NewDepartment {
            get {
                return ResourceManager.GetString("CallFlowView_NewDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pick up the call... 的本地化字符串。
        /// </summary>
        internal static string CallFlowView_PickUpCall {
            get {
                return ResourceManager.GetString("CallFlowView_PickUpCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Play a Greeting 的本地化字符串。
        /// </summary>
        internal static string CallFlowView_PlayGreeting {
            get {
                return ResourceManager.GetString("CallFlowView_PlayGreeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transfer to Extension {0} 的本地化字符串。
        /// </summary>
        internal static string CallFlowView_TransferExt {
            get {
                return ResourceManager.GetString("CallFlowView_TransferExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transfer to {0} 的本地化字符串。
        /// </summary>
        internal static string CallFlowView_TransferNum {
            get {
                return ResourceManager.GetString("CallFlowView_TransferNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown Extension 的本地化字符串。
        /// </summary>
        internal static string CallFlowView_UnknownExt {
            get {
                return ResourceManager.GetString("CallFlowView_UnknownExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Welcome your caller 的本地化字符串。
        /// </summary>
        internal static string CallFlowView_WelcomeCaller {
            get {
                return ResourceManager.GetString("CallFlowView_WelcomeCaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Welcome Greeting 的本地化字符串。
        /// </summary>
        internal static string CallFlowView_WelcomeGreeting {
            get {
                return ResourceManager.GetString("CallFlowView_WelcomeGreeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Welcome to [Your Company Name] 的本地化字符串。
        /// </summary>
        internal static string CallFlowView_WelcomeTo {
            get {
                return ResourceManager.GetString("CallFlowView_WelcomeTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to clear the call history? 的本地化字符串。
        /// </summary>
        internal static string CallHistoryView_ConfirmClear {
            get {
                return ResourceManager.GetString("CallHistoryView_ConfirmClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to find an Outlook contact that matches this caller. Would you like to create a new contact with this information? 的本地化字符串。
        /// </summary>
        internal static string CallHistoryView_ContactNotFound {
            get {
                return ResourceManager.GetString("CallHistoryView_ContactNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Contact Found 的本地化字符串。
        /// </summary>
        internal static string CallHistoryView_NoContactFound {
            get {
                return ResourceManager.GetString("CallHistoryView_NoContactFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Changing CallButler Edition. Please wait while the service restarts. 的本地化字符串。
        /// </summary>
        internal static string Common_ChangingEdition {
            get {
                return ResourceManager.GetString("Common_ChangingEdition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        internal static string Common_Close {
            get {
                return ResourceManager.GetString("Common_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm Delete 的本地化字符串。
        /// </summary>
        internal static string Common_ConfirmDelete {
            get {
                return ResourceManager.GetString("Common_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        internal static string Common_Delete {
            get {
                return ResourceManager.GetString("Common_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit... 的本地化字符串。
        /// </summary>
        internal static string Common_Edit {
            get {
                return ResourceManager.GetString("Common_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Email Error 的本地化字符串。
        /// </summary>
        internal static string Common_EmailError {
            get {
                return ResourceManager.GetString("Common_EmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There was a problem sending an Email to {0}
        ///
        ///Please check your mail settings and try again.
        ///
        ///Error Detail:
        ///{1} 的本地化字符串。
        /// </summary>
        internal static string Common_EmailProblem {
            get {
                return ResourceManager.GetString("Common_EmailProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Email Sent 的本地化字符串。
        /// </summary>
        internal static string Common_EmailSent {
            get {
                return ResourceManager.GetString("Common_EmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Email was successfully sent to  的本地化字符串。
        /// </summary>
        internal static string Common_EmailSentTo {
            get {
                return ResourceManager.GetString("Common_EmailSentTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter a valid Email address 的本地化字符串。
        /// </summary>
        internal static string Common_EnterValidEmail {
            get {
                return ResourceManager.GetString("Common_EnterValidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid Email Address 的本地化字符串。
        /// </summary>
        internal static string Common_InvalidEmail {
            get {
                return ResourceManager.GetString("Common_InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter your name. 的本地化字符串。
        /// </summary>
        internal static string Common_NameRequired {
            get {
                return ResourceManager.GetString("Common_NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No 的本地化字符串。
        /// </summary>
        internal static string Common_No {
            get {
                return ResourceManager.GetString("Common_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password Mismatch 的本地化字符串。
        /// </summary>
        internal static string Common_PasswordMismatch {
            get {
                return ResourceManager.GetString("Common_PasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Passwords do not match. Please re-enter your password and confirm it. 的本地化字符串。
        /// </summary>
        internal static string Common_PasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("Common_PasswordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Permission Denied 的本地化字符串。
        /// </summary>
        internal static string Common_PermissionDenied {
            get {
                return ResourceManager.GetString("Common_PermissionDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter your phone number. 的本地化字符串。
        /// </summary>
        internal static string Common_PhoneNumberRequired {
            get {
                return ResourceManager.GetString("Common_PhoneNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select a country. 的本地化字符串。
        /// </summary>
        internal static string Common_SelectCountry {
            get {
                return ResourceManager.GetString("Common_SelectCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sending data... 的本地化字符串。
        /// </summary>
        internal static string Common_SendingData {
            get {
                return ResourceManager.GetString("Common_SendingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yes 的本地化字符串。
        /// </summary>
        internal static string Common_Yes {
            get {
                return ResourceManager.GetString("Common_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your telephone provider settings have been successfully imported. 的本地化字符串。
        /// </summary>
        internal static string Configruation_ProviderSettingsLoaded {
            get {
                return ResourceManager.GetString("Configruation_ProviderSettingsLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This CallButler configuration file appears to be invalid and cannot be loaded. 的本地化字符串。
        /// </summary>
        internal static string Configruation_UnableToLoad {
            get {
                return ResourceManager.GetString("Configruation_UnableToLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add-on Module Settings 的本地化字符串。
        /// </summary>
        internal static string DepartmentForm_AddonModuleSettings {
            get {
                return ResourceManager.GetString("DepartmentForm_AddonModuleSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extension Settings 的本地化字符串。
        /// </summary>
        internal static string DepartmentForm_ExtensionSettings {
            get {
                return ResourceManager.GetString("DepartmentForm_ExtensionSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Message Settings 的本地化字符串。
        /// </summary>
        internal static string DepartmentForm_MessageSettings {
            get {
                return ResourceManager.GetString("DepartmentForm_MessageSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Number Settings 的本地化字符串。
        /// </summary>
        internal static string DepartmentForm_NumberSettings {
            get {
                return ResourceManager.GetString("DepartmentForm_NumberSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Script Settings 的本地化字符串。
        /// </summary>
        internal static string DepartmentForm_ScriptSettings {
            get {
                return ResourceManager.GetString("DepartmentForm_ScriptSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A test Email was successfully sent to {0}
        ///
        ///Check your Email in a few minutes to confirm the receipt of this message. 的本地化字符串。
        /// </summary>
        internal static string EmailUtils_EmailSuccess {
            get {
                return ResourceManager.GetString("EmailUtils_EmailSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This is a test message sent by CallButler.
        ///
        ///If you received this Email, your SMTP Email settings are correct. 的本地化字符串。
        /// </summary>
        internal static string EmailUtils_TestEmail {
            get {
                return ResourceManager.GetString("EmailUtils_TestEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CallButler Test Message 的本地化字符串。
        /// </summary>
        internal static string EmailUtils_TestEmailSubject {
            get {
                return ResourceManager.GetString("EmailUtils_TestEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Contact your administrator 的本地化字符串。
        /// </summary>
        internal static string ExtensionEditorForm_ContactAdmin {
            get {
                return ResourceManager.GetString("ExtensionEditorForm_ContactAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Email Configuration 的本地化字符串。
        /// </summary>
        internal static string ExtensionEditorForm_EmailConfiguration {
            get {
                return ResourceManager.GetString("ExtensionEditorForm_EmailConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Before sending Emails, CallButler must be configured for your SMTP Email Server.
        ///
        ///Would you like to do this now? 的本地化字符串。
        /// </summary>
        internal static string ExtensionEditorForm_EnterSMTP {
            get {
                return ResourceManager.GetString("ExtensionEditorForm_EnterSMTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please specify an Email address to which to send this Email 的本地化字符串。
        /// </summary>
        internal static string ExtensionEditorForm_PleaseSpecifyEmail {
            get {
                return ResourceManager.GetString("ExtensionEditorForm_PleaseSpecifyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your new telephone Extension 的本地化字符串。
        /// </summary>
        internal static string ExtensionEditorForm_YourNewExtension {
            get {
                return ResourceManager.GetString("ExtensionEditorForm_YourNewExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This version of CallButler does not allow more than {0} extensions.
        ///If you would like to add more extensions, you may need to upgrade. 的本地化字符串。
        /// </summary>
        internal static string ExtensionsView_ExtLimit {
            get {
                return ResourceManager.GetString("ExtensionsView_ExtLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure want to delete this Extension?
        ///
        ///This will also delete any voicemail boxes associated with this Extension. 的本地化字符串。
        /// </summary>
        internal static string ExtensionView_ConfirmDelete {
            get {
                return ResourceManager.GetString("ExtensionView_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extension Number Conflict 的本地化字符串。
        /// </summary>
        internal static string ExtensionView_ExtConflict {
            get {
                return ResourceManager.GetString("ExtensionView_ExtConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Extension number {0} is already taken. This Extension number has been changed to {1} for you. 的本地化字符串。
        /// </summary>
        internal static string ExtensionView_ExtTaken {
            get {
                return ResourceManager.GetString("ExtensionView_ExtTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Retreiving sounds... 的本地化字符串。
        /// </summary>
        internal static string GreetingUtils_GettingSounds {
            get {
                return ResourceManager.GetString("GreetingUtils_GettingSounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Saving sounds... 的本地化字符串。
        /// </summary>
        internal static string GreetingUtils_SavingSounds {
            get {
                return ResourceManager.GetString("GreetingUtils_SavingSounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Asterisk Servers 的本地化字符串。
        /// </summary>
        internal static string InventoryControl_AsteriskServerList {
            get {
                return ResourceManager.GetString("InventoryControl_AsteriskServerList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The username and/or password you have specified is invalid. Please try again.  的本地化字符串。
        /// </summary>
        internal static string LoginForm_InvalidLogin {
            get {
                return ResourceManager.GetString("LoginForm_InvalidLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid Login 的本地化字符串。
        /// </summary>
        internal static string LoginForm_InvalidLoginTitle {
            get {
                return ResourceManager.GetString("LoginForm_InvalidLoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The password you entered appears to be incorrect.
        ///
        ///Please try again. 的本地化字符串。
        /// </summary>
        internal static string MainForm_BadPassword {
            get {
                return ResourceManager.GetString("MainForm_BadPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CallButler Service 的本地化字符串。
        /// </summary>
        internal static string MainForm_CallButlerService {
            get {
                return ResourceManager.GetString("MainForm_CallButlerService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Changes saved 的本地化字符串。
        /// </summary>
        internal static string MainForm_ChangesSaved {
            get {
                return ResourceManager.GetString("MainForm_ChangesSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to turn on expert mode?
        ///
        ///Expert mode should only be used by advanced users and may temporarily disable CallButler from answering calls.
        ///     的本地化字符串。
        /// </summary>
        internal static string MainForm_ChangeToExpertMode {
            get {
                return ResourceManager.GetString("MainForm_ChangeToExpertMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change to Expert Mode? 的本地化字符串。
        /// </summary>
        internal static string MainForm_ChangeToExpertModeCaption {
            get {
                return ResourceManager.GetString("MainForm_ChangeToExpertModeCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connected to {0} 的本地化字符串。
        /// </summary>
        internal static string MainForm_ConnectedTo {
            get {
                return ResourceManager.GetString("MainForm_ConnectedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connecting to {0} 的本地化字符串。
        /// </summary>
        internal static string MainForm_ConnectingTo {
            get {
                return ResourceManager.GetString("MainForm_ConnectingTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You have entered an invalid license Key. Please try again. 的本地化字符串。
        /// </summary>
        internal static string MainForm_EnteredBadLicense {
            get {
                return ResourceManager.GetString("MainForm_EnteredBadLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You have enetered an expired trial license. Please try again. 的本地化字符串。
        /// </summary>
        internal static string MainForm_EnteredExpiredLicense {
            get {
                return ResourceManager.GetString("MainForm_EnteredExpiredLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This trial version of CallButler has expired and will no longer answer calls 的本地化字符串。
        /// </summary>
        internal static string MainForm_Expired {
            get {
                return ResourceManager.GetString("MainForm_Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This trial license will expire on {0} 的本地化字符串。
        /// </summary>
        internal static string MainForm_ExpireOnDate {
            get {
                return ResourceManager.GetString("MainForm_ExpireOnDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This trial license for CallButler will expire in {0} day(s) 的本地化字符串。
        /// </summary>
        internal static string MainForm_Expires {
            get {
                return ResourceManager.GetString("MainForm_Expires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid License Key 的本地化字符串。
        /// </summary>
        internal static string MainForm_InvalidLicenseKey {
            get {
                return ResourceManager.GetString("MainForm_InvalidLicenseKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 License Validated 的本地化字符串。
        /// </summary>
        internal static string MainForm_LicenseValidated {
            get {
                return ResourceManager.GetString("MainForm_LicenseValidated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading data... 的本地化字符串。
        /// </summary>
        internal static string MainForm_LoadingData {
            get {
                return ResourceManager.GetString("MainForm_LoadingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No connection 的本地化字符串。
        /// </summary>
        internal static string MainForm_NoConnection {
            get {
                return ResourceManager.GetString("MainForm_NoConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The CallButler Service you are connecting to does not allow management from remote computers. 的本地化字符串。
        /// </summary>
        internal static string MainForm_RemoteManagementError {
            get {
                return ResourceManager.GetString("MainForm_RemoteManagementError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remote Management Error 的本地化字符串。
        /// </summary>
        internal static string MainForm_RemoteManagementErrorCaption {
            get {
                return ResourceManager.GetString("MainForm_RemoteManagementErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Saving changes... 的本地化字符串。
        /// </summary>
        internal static string MainForm_SavingChanges {
            get {
                return ResourceManager.GetString("MainForm_SavingChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The CallButler Service does not appear to be installed on this computer.
        ///
        ///If it is installed, you may need to start the service manually. 的本地化字符串。
        /// </summary>
        internal static string MainForm_ServiceNotFound {
            get {
                return ResourceManager.GetString("MainForm_ServiceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The CallButler Service does not appear to be running on this computer.
        ///
        ///Would you like to start the CallButler Service? 的本地化字符串。
        /// </summary>
        internal static string MainForm_ServiceNotRunning {
            get {
                return ResourceManager.GetString("MainForm_ServiceNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Starting the CallButler Service 的本地化字符串。
        /// </summary>
        internal static string MainForm_StartingService {
            get {
                return ResourceManager.GetString("MainForm_StartingService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Thank you for registering this copy of CallButler. 的本地化字符串。
        /// </summary>
        internal static string MainForm_ThankYouForReg {
            get {
                return ResourceManager.GetString("MainForm_ThankYouForReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Trial License 的本地化字符串。
        /// </summary>
        internal static string MainForm_TrialLicense {
            get {
                return ResourceManager.GetString("MainForm_TrialLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The CallButler service you are trying to connect to is not available.
        ///
        ///Please check to make sure the server name or IP address is correct and try again. 的本地化字符串。
        /// </summary>
        internal static string MainForm_UnableToConnect {
            get {
                return ResourceManager.GetString("MainForm_UnableToConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The CallButler User Manual does not appear to be installed on this computer. 的本地化字符串。
        /// </summary>
        internal static string MainForm_UnableToFindUserManual {
            get {
                return ResourceManager.GetString("MainForm_UnableToFindUserManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Waiting for CallButler Service to start. 的本地化字符串。
        /// </summary>
        internal static string MainForm_WaitingForService {
            get {
                return ResourceManager.GetString("MainForm_WaitingForService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to remove the selected hold music? 的本地化字符串。
        /// </summary>
        internal static string MusicSettings_ConfirmRemoveMusic {
            get {
                return ResourceManager.GetString("MusicSettings_ConfirmRemoveMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to delete this call personalization? 的本地化字符串。
        /// </summary>
        internal static string PersonalizedGreetingView_ConfirmDelete {
            get {
                return ResourceManager.GetString("PersonalizedGreetingView_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Finish 的本地化字符串。
        /// </summary>
        internal static string PrebuiltConfigForm_Finish {
            get {
                return ResourceManager.GetString("PrebuiltConfigForm_Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Next &gt; 的本地化字符串。
        /// </summary>
        internal static string PrebuiltConfigForm_Next {
            get {
                return ResourceManager.GetString("PrebuiltConfigForm_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Initializing... 的本地化字符串。
        /// </summary>
        internal static string Program_Initializing {
            get {
                return ResourceManager.GetString("Program_Initializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to delete this provider? 的本地化字符串。
        /// </summary>
        internal static string ProvidersView_ConfirmDelete {
            get {
                return ResourceManager.GetString("ProvidersView_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Is Receptionist 的本地化字符串。
        /// </summary>
        internal static string Receptionist_IsReceptionist {
            get {
                return ResourceManager.GetString("Receptionist_IsReceptionist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        internal static string RecordVoicePrompt_Delete {
            get {
                return ResourceManager.GetString("RecordVoicePrompt_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Play 的本地化字符串。
        /// </summary>
        internal static string RecordVoicePrompt_Play {
            get {
                return ResourceManager.GetString("RecordVoicePrompt_Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RecordAgain 的本地化字符串。
        /// </summary>
        internal static string RecordVoicePrompt_RecordAgain {
            get {
                return ResourceManager.GetString("RecordVoicePrompt_RecordAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Print Error 的本地化字符串。
        /// </summary>
        internal static string ReportPrinter_PrintError {
            get {
                return ResourceManager.GetString("ReportPrinter_PrintError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to print report.
        ///
        /// 的本地化字符串。
        /// </summary>
        internal static string ReportPrinter_UnableToPrint {
            get {
                return ResourceManager.GetString("ReportPrinter_UnableToPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure want to delete this script schedule? 的本地化字符串。
        /// </summary>
        internal static string ScriptScheduleView_ConfirmDelete {
            get {
                return ResourceManager.GetString("ScriptScheduleView_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Script Schedule 的本地化字符串。
        /// </summary>
        internal static string ScriptScheduleView_NewSchedule {
            get {
                return ResourceManager.GetString("ScriptScheduleView_NewSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Uploading music...
        ///This may take a few moments. 的本地化字符串。
        /// </summary>
        internal static string SettingsView_UploadingMusic {
            get {
                return ResourceManager.GetString("SettingsView_UploadingMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown Caller 的本地化字符串。
        /// </summary>
        internal static string SummaryView_UnkownCaller {
            get {
                return ResourceManager.GetString("SummaryView_UnkownCaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Call Transfer 的本地化字符串。
        /// </summary>
        internal static string TestDriveView_CallTransfer {
            get {
                return ResourceManager.GetString("TestDriveView_CallTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CallButler Test Call 的本地化字符串。
        /// </summary>
        internal static string TestDriveView_CBTestCall {
            get {
                return ResourceManager.GetString("TestDriveView_CBTestCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connected 的本地化字符串。
        /// </summary>
        internal static string TestDriveView_Connected {
            get {
                return ResourceManager.GetString("TestDriveView_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Press the call button to begin... 的本地化字符串。
        /// </summary>
        internal static string TestDriveView_PressToCall {
            get {
                return ResourceManager.GetString("TestDriveView_PressToCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ready for Call 的本地化字符串。
        /// </summary>
        internal static string TestDriveView_ReadyForCall {
            get {
                return ResourceManager.GetString("TestDriveView_ReadyForCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This call would now be transferred to {0} but this test cannot simulate that.
        ///
        ///The call will now hang up. 的本地化字符串。
        /// </summary>
        internal static string TestDriveView_TransferSim {
            get {
                return ResourceManager.GetString("TestDriveView_TransferSim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The numbered Extension, i.e. 1234, that will be associated with this particular User / Phone. 的本地化字符串。
        /// </summary>
        internal static string Tooltips_Users_Extension_Text {
            get {
                return ResourceManager.GetString("Tooltips_Users_Extension_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extensions 的本地化字符串。
        /// </summary>
        internal static string Tooltips_Users_Extension_Title {
            get {
                return ResourceManager.GetString("Tooltips_Users_Extension_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your new version of CallButler has been downloaded.
        ///
        ///Would you like to install this new version now? 的本地化字符串。
        /// </summary>
        internal static string VersionCheckeForm_FinishedDownload {
            get {
                return ResourceManager.GetString("VersionCheckeForm_FinishedDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download Complete 的本地化字符串。
        /// </summary>
        internal static string VersionCheckerForm_DownloadComplete {
            get {
                return ResourceManager.GetString("VersionCheckerForm_DownloadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download Error 的本地化字符串。
        /// </summary>
        internal static string VersionCheckerForm_DownloadError {
            get {
                return ResourceManager.GetString("VersionCheckerForm_DownloadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Downloading the latest version of CallButler 的本地化字符串。
        /// </summary>
        internal static string VersionCheckerForm_Downloading {
            get {
                return ResourceManager.GetString("VersionCheckerForm_Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You are not running the latest version of CallButler.
        ///We recommend that you download the latest version. 的本地化字符串。
        /// </summary>
        internal static string VersionCheckerForm_NotOnLatest {
            get {
                return ResourceManager.GetString("VersionCheckerForm_NotOnLatest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There was a problem downloading the new version of CallButler. Please contact support@callbutler.com. 的本地化字符串。
        /// </summary>
        internal static string VersionCheckerForm_ProblemDownloading {
            get {
                return ResourceManager.GetString("VersionCheckerForm_ProblemDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You are running the latest version of CallButler. 的本地化字符串。
        /// </summary>
        internal static string VersionCheckerForm_RunningLatest {
            get {
                return ResourceManager.GetString("VersionCheckerForm_RunningLatest", resourceCulture);
            }
        }
    }
}
