//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.1434
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisualAsterisk.Main {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class VisualAsteriskChanges : global::System.Configuration.ApplicationSettingsBase {
        
        private static VisualAsteriskChanges defaultInstance = ((VisualAsteriskChanges)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new VisualAsteriskChanges())));
        
        public static VisualAsteriskChanges Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>bug fix1</string>\r\n  <string>bug fix2</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Bugfixes {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Bugfixes"]));
            }
            set {
                this["Bugfixes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>feature 1</string>\r\n  <string>feature 2</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Features {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Features"]));
            }
            set {
                this["Features"] = value;
            }
        }
    }
}
